// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiUy3ZNVZ6n5ppkeX837sSrNjCbWlT80',
    appId: '1:990697078228:web:ca46f267f66fde5ca3aa41',
    messagingSenderId: '990697078228',
    projectId: 'fruits-hub-ecommerce',
    authDomain: 'fruits-hub-ecommerce.firebaseapp.com',
    storageBucket: 'fruits-hub-ecommerce.firebasestorage.app',
    measurementId: 'G-Y9EK281RF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7VNf-jvqc92huMp78qx1vRsjMKZ8Al8',
    appId: '1:990697078228:android:1223726b073249f4a3aa41',
    messagingSenderId: '990697078228',
    projectId: 'fruits-hub-ecommerce',
    storageBucket: 'fruits-hub-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0EgUVwUOFS68WrZMIh1nedeilWPlBL-E',
    appId: '1:990697078228:ios:55180a0db804d91da3aa41',
    messagingSenderId: '990697078228',
    projectId: 'fruits-hub-ecommerce',
    storageBucket: 'fruits-hub-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0EgUVwUOFS68WrZMIh1nedeilWPlBL-E',
    appId: '1:990697078228:ios:55180a0db804d91da3aa41',
    messagingSenderId: '990697078228',
    projectId: 'fruits-hub-ecommerce',
    storageBucket: 'fruits-hub-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtiUy3ZNVZ6n5ppkeX837sSrNjCbWlT80',
    appId: '1:990697078228:web:cdeddd17dc1ed461a3aa41',
    messagingSenderId: '990697078228',
    projectId: 'fruits-hub-ecommerce',
    authDomain: 'fruits-hub-ecommerce.firebaseapp.com',
    storageBucket: 'fruits-hub-ecommerce.firebasestorage.app',
    measurementId: 'G-PRS3KC99X1',
  );
}
